/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlotPanel.java
 *
 * Created on Jan 27, 2009, 8:16:49 AM
 */

package complexplot;
import java.awt.*;
import java.text.DecimalFormat;

/**
 *
 * @author SCHEIBER
 */
public class PlotPanel extends javax.swing.JPanel {

  /** Creates new form PlotPanel */
  public PlotPanel(DataIn din, Image image, String name) {
    int P=din.getP();
    int Q=din.getQ();
    initComponents();
    jLabelName.setText(name);
    DecimalFormat f=new DecimalFormat("#0.0");
    String txt=f.format(din.getXm());
    jLabelXm.setText(txt);
    //jLabelXm.setLocation(20,Q+10);
    txt=f.format(din.getXM());
    jLabelXM.setText(txt);
    //jLabelXM.setLocation(2*P,Q+10);
    txt=f.format(din.getYm());
    jLabelYm.setText(txt);
    //jLabelYm.setLocation(5,2*Q);
    txt=f.format(din.getYM());
    jLabelYM.setText(txt);
    //jLabelYM.setLocation(5,10);
    MyCanvas mc=new MyCanvas(image);
    jPanelCanvas.setPreferredSize(new Dimension(din.getP(),din.getQ()));
    //Dimension d=jPanelCanvas.getSize();
    //System.out.println(d.width+" "+d.height);
    jPanelCanvas.setLayout(new BorderLayout());
    jPanelCanvas.add(mc,BorderLayout.CENTER);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelYM = new javax.swing.JLabel();
    jLabelYm = new javax.swing.JLabel();
    jLabelXm = new javax.swing.JLabel();
    jLabelXM = new javax.swing.JLabel();
    jPanelCanvas = new javax.swing.JPanel();
    jLabelName = new javax.swing.JLabel();

    jLabelYM.setText("jLabel1");

    jLabelYm.setText("jLabel2");

    jLabelXm.setText("jLabel3");

    jLabelXM.setText("jLabel4");

    jPanelCanvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanelCanvas.setPreferredSize(new java.awt.Dimension(400, 400));

    javax.swing.GroupLayout jPanelCanvasLayout = new javax.swing.GroupLayout(jPanelCanvas);
    jPanelCanvas.setLayout(jPanelCanvasLayout);
    jPanelCanvasLayout.setHorizontalGroup(
      jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 398, Short.MAX_VALUE)
    );
    jPanelCanvasLayout.setVerticalGroup(
      jPanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 398, Short.MAX_VALUE)
    );

    jLabelName.setText("name");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabelYM)
          .addComponent(jLabelYm))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelXm)
            .addGap(153, 153, 153)
            .addComponent(jLabelName)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelXM))
          .addComponent(jPanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(141, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelYM)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelYm))
          .addComponent(jPanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabelXm)
            .addComponent(jLabelXM))
          .addComponent(jLabelName))
        .addContainerGap(116, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabelName;
  private javax.swing.JLabel jLabelXM;
  private javax.swing.JLabel jLabelXm;
  private javax.swing.JLabel jLabelYM;
  private javax.swing.JLabel jLabelYm;
  private javax.swing.JPanel jPanelCanvas;
  // End of variables declaration//GEN-END:variables

}
